### ISSUE TITLE
Install on Ubuntu 22.x

### ISSUE THREAD

**Issue by jduan00** [gene-git/wg_tool#10]

**Comment by jduan00** [comment]
Actually solved the issue. Perhaps these instructions can be added to the documentation for Ubuntu users.

apt install python3

**Comment by gene-git** [comment]
Did you get it working okay? Let me know if I can help in some way.

**Comment by jduan00** [comment]
Hi Gene,

Thanks for the super fast response. I did get this to work on Ubuntu as I am not an expert with Python, I had some work to do to get Python3 and pip installed, then built and installed the package. 

`wg-tool` indeed solves a real problem, that is to make managing keys and confing so much easier. Thank you!

Two things I found:

1. iOS clients cannot resolve host names, thus I had to put in the IP for the server endpoint.
2. I have special `iptable` rules setup, so no need to do PostUp or Down. Since `wg-tool` expects these to be there, thus I put in the following:

```
PostUp = "/usr/bin/true"
PostDown = "/usr/bin/true"
```

Thank you again for making this useful tool available to all. Wishing you the very best!

Jack

**Comment by gene-git** [comment]
Glad you got it working - would be nice if someone packaged it up for ubuntu.

Interesting about ios clients - i know other iphone users using hostnames and it works fine for them.

Assuming the (fully qualified) hostname is available in public dns , Does "dig <vpn-hostname>" say anythnng useful?

Thanks for update.

gene

**Comment by gene-git** [comment]
By the way - if you have any linux laptop users you may find wg-client useful as well.
https://github.com/gene-git/wg-client

**Comment by jduan00** [comment]
You are right. I tried again on iOS, hostname.example.com does work! Thanks!
