### ISSUE TITLE
The hostname variable does not modify the endpoint variable for existing user profiles.

### ISSUE THREAD

**Issue by Antynea** [gene-git/wg_tool#11]
Hello,

The ip address used by my wiregard server will have to be changed.
Modified hostname variable in `/etc/wireguard/wg-tool/server/server.conf`, works for all new profiles added, but does not modify existing profiles.
How can I update existing profiles with the new hostname value ?

**Comment by gene-git** [comment]
Update will be uploaded shortly.   To get the user profile endpoint updated you will then run:

```
    wg-tool -mod -upd user:profile
or
   wg-tool --mod_users --upd_endpoint user:profile
```

**Comment by Antynea** [comment]
Will we be able to use the `-all` argument to update all existing user profiles ?
`wg-tool -all -upd`

**Comment by gene-git** [comment]
Yes - this will apply to all profiles:

```
wg-tool -mod -upd -all
```

**Comment by gene-git** [comment]
I pushed the changes - let me know if this is okay.

thanks !

**Comment by Antynea** [comment]
`wg-tool -mod -upd -all`  works like a charm.
Many thanks, your tool is very useful.

**Comment by gene-git** [comment]
Great and thank you for bringing this to my attention. 

Aside - you may also find wg-client useful if you have linux laptop users (https://github.com/gene-git/wg-client) an aur.
