### ISSUE TITLE
having an established location for the config files (enhancement)

### ISSUE THREAD

**Issue by ycardon** [gene-git/wg_tool#4]
Currently the default working directory of `wg-tool` is `./`, witch makes user to take care of either where the command is called or add the extra `-wkd` argument.

How about fixing the location of the config files? This would allow: 
- to launch `wg-tool` from anywhere without fear of mistake
- optionally to propose the user to softlink `/etc/wireguard/wg0.conf` to  ...`/wg-configs/server/wg0.conf`

I'm not sure where the location could be. `/etc/wireguard/wg-tool/`?

**Comment by gene-git** [comment]
Good suggestions 

1) working dir
    Yes agree - been thinking about that as well. I do want to maintain backward compatibility whenever humanly possible so we don't break current users who may, for example, have set up their config elsewhere and now do "cd /foo; wg-tool .."

    How about I make the working dir instead a  path - where we the default is:

    "./:/etc/wireguard/wg-tool"
   This allows us to soft link /etc/wireguard/wg-tool elsewhere of course. 
   This would add a standard place but keep "./" first in search path to remain backward compatible with current usage.
   After a sufficiently long period of time we can consider remove "./" from path - giving users time to adjust.
   
   What you think? 

2) symlink of live wg0.,conf
     Should be fine too  as we keep history of all configs (until user deletes them anyway) - and prev config is readily available in same dir as the latest config.  Some may choose to only update manually, as is the case now.

**Comment by ycardon** [comment]
+1 for backward compatibility. 

Sequential lookup for configuration seems to be a good option, very similar to many existing tools ($XDG_CONFIG style). I would first look for `/etc/wireguard/wg-tool/`and then `./`, it will keep backward compatibility but feel more predictable and error prone.

`/etc/wireguard/wg-tool/` could be created during first initialisation `wg-tool --init` with safe access rights (700), symlink `wg0.conf` being an option.

Regarding the location of the config dir, `/etc/` root is dedicated to server config made by administrators, so it's the good place. I was wondering if `/etc/wireguard/wg-tool` would interfere in any way with other wireguard tools, I don't have sufficient knowledge about the ecosystem to answer. `/etc/wg-tool` is also an option, less intricated with `wg-quick`.

You may also consider about keeping scripts under `$WG_TOOL_HOME/scripts`... I'm really not sure about this, that will depend whether you consider wg-tool is about to create config for wg-quick or a more generic tool. Maybe for feedback from the community would be great.

Anyway thank you for this piece of software and your reactivity.

**Comment by gene-git** [comment]
(i) You're ight - better to do dir search order as you suggest with "./" being second.

(ii) I am actually working on setting tighter permissions - will be in next push - will be u=rwX,g=rw,

(iii) As for scripts - whether for server or client mode - both are consumed by wg-quick (or wg really) - so I do  think it makes sense for them to remain in /etc/wireguard/scripts. 
Also,  it's quite possible to have Linux clients who have not installed wg-tool at all, but are using wireguard with config provided to them. 

(iv) /etc/wireguard/wg-tool vs /etc/wg-tool
      Don't think it interferes in anyway with wireguard itself - and arch pacman should be fine with it as well.
      Makes sense to keep all the wireguard files in one place - and /etc/wireguard/wg-tool seems reasonable.

thanks for improving wg-tool :)

**Comment by gene-git** [comment]
Pushed update - please test and let me know if is ok or of any issues. 
Thanks!

**Comment by ycardon** [comment]
working good so far :)

thanks a lot, it's much more easy to manage like it is now!

**Comment by gene-git** [comment]
Thank you for the suggestions  - and sure please close if you're comfortable.
