### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by merger3** [gene-git/wg_tool#8]
Is there a way to have the clients automatically configure with IPv6? The tool seems to only generate IPv4 addresses for the clients.

Awesome work on the tool, it's so good it feels like a suite of tools that should be natively built into the protocol.

**Comment by gene-git** [comment]
Hi 

When a user:profile is created an available IP is chosen.  The way it's chosen is by taking the first listed network from the server Address config. So if the server config has for example:

      Address =   ['10.99.99.1/24', 'fc00:99:99::1/64']

Then client IPs will be picked from '10.99.99.1/24'. by default.

So can you try simply changing the server config by switching the order of IPv4 and IPv6,  so the IPv6 addresses are first in the list. For above example it would be:

       Address = [ 'fc00:99:99::1/64',  '10.99.99.1/24']

Just manually edit the 'configs/server/server.conf' file to do it.

Please let me know if that works?

thanks for  positive feedback !

**Comment by gene-git** [comment]
I released version 5.1.0 which should work properly now with IPv6.

Please let me know if it now works for you.

thanks!

**Comment by gene-git** [comment]
I am closing this one as I believe it's solved. Please do let me know if you still have any problems.

Thanks again for letting me know about the issue.

**Comment by ioangogo** [comment]
It does seem to work, although there seems to currently be an issue where only one address assigned to a client, Where as Wireguard does allow for a client to have multiple addresses

**Comment by gene-git** [comment]
Very good point - let me think a bit how to add a new feature to support this.

**Comment by gene-git** [comment]
To ensure I do this properly, please can you share the use case you have in mind?

**Comment by ioangogo** [comment]
A dual Stack tunnel that has both IPv4 and IPv6 addresses

here is a example client config from my old setup where i was making use of this feature, i had only 2 addresses in there(ipv4 and IPv6) but i beleive that it can do more than that

```ini
[Interface]
PrivateKey =
Address = 192.168.15.6/24, [public_prefix]::6/128
DNS = 8.8.8.8, 192.168.1.144

[Peer]
PublicKey = 
Endpoint = [personal domain].co.uk:51820
AllowedIPs = 0.0.0.0/0, ::/0
```

**Comment by gene-git** [comment]
Thanks.
Opened new issue #14

**Comment by gene-git** [comment]
@ioangogo I'll be releasing an update fairly soon - let me know your thoughts in issue #14.

thanks

**Comment by gene-git** [comment]
version 6.0.0 pushed
