### ISSUE TITLE
Why are there 2 hostnames (Hostname and Hostname_Int)?

### ISSUE THREAD

**Issue by schmodd** [gene-git/wg_tool#9]
I dont understand why there are 2 values for hostnames. Both are "key fields to edit". Do I have to fill both? How can I determine which one of these hostname fields is used as Endpoint for the userconfigs?
In my case the Hostname_Int ends up in my userconfig Endpoint - making it impossible for me to connect to the wireguard-server.

**Comment by gene-git** [comment]
Hostname is the 'external' hostname  wireguard clients  use when roaming (i.e. from internet)

In the event you want to access wireguard from inside your internal network then you can optionally use Hostname_Int as well. This can be useful for testing the wireguard server purely on internal network.  I use it to make sure things work properly before testing from the internet (external)  - this checks any  firewall is correctly passing the packets back to the wireguard server.

Hostname_Int is optional.

For making client configs you do 

    wg-tool --add user:profile

the vpn server will be Hostname. If imnstead you use:

    wg-tool -add -int user_test:profile

Then the newly generated config will use Hostname_Int instead

See 'wg-tool -h' for more help.

Does that help sort things out?

**Comment by schmodd** [comment]
Thank you for the quick reply and clarification.

**Comment by schmodd** [comment]
Thank you for the quick reply and clarification.

**Comment by gene-git** [comment]
By the way if your internal DNS maps the external Hostname to an internal IP when inside your local network and external IP when outside, then the same config will work internal or external - which is nicer as well as simpler.

Happy to help - let me know if anything else I can help with. Happy new year!

**Comment by gene-git** [comment]
Thanks for your feedback -  makes it clear I should improve the docs  too :)
